### ISSUE TITLE
[FR] error-prone check to prefer minimally specific interfaces where possible??

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#1888]
## What happened?

Internally, config is exposed as a [`Refreshable<T>`](https://github.com/palantir/refreshable/blob/develop/src/main/java/com/palantir/refreshable/Refreshable.java). It extends `Supplier<T>`, so it's a well known best-practise that when you're writing a class that depends on some config, you should use the `Supplier<T>` constructor arg if possible, instead of the `Refreshable<T>` constructor arg because this makes testing easier, and emphasises to readers that you only use the simple '.get()' method.

```java
public MyThingy(Refreshable<AuthHeader> auth, ...) { // ❌  bad

public MyThingy(Supplier<AuthHeader> auth, ...) { // ✅. good
```

In fact, the only reason to use the `Refreshable` interface is if you _really need_ the advanced methods like `map` and `subscribe`. Unfortunately I've found a _bunch_ of classes in Apollo that seem to pass in `Refreshable<T>` when `Supplier<T>` would have been perfectly adequate.

This got me thinking, could this be enforced using an error-prone rule???? 

## What did you want to happen?

Error-prone should detect constructors/private final fields which use overly specific interfaces like Refreshable, and suggest substituting the parent interface (i.e. Supplier). 

I'm not sure if this is actually prohibitively complicated to write, but just wanted to float the idea.

**Comment by carterkozak** [comment]
Hmm, I don't think we can be confident enough that recommendations are reasonable in enough cases that this sort of check will be worthwhile to roll out and support. I agree with the direction, that it's a sane default, but I don't know if the pay-off is worth the friction it would introduce.

For example, the following would likely be recommended in some cases, but certainly isn't what we're looking for!
```diff
- public MyThingy(SafeArg<String> name, ...) { // ✅. good
+ public MyThingy(Arg<String> name, ...) { // ❌  bad
```

Using a more specific type is generally a good way to rule out interfaces that aren't aware of our contract, so I may prefer to take a `NonBlockingStringSupplier` instead of `Supplier<String>` because it forces the caller to acknowledge a more specific contract. This argument can be expanded to Refreshable due to the contract around `get` always working as a volatile read while another supplier implementation may result in some form of work (the `Gauge<?>` metric problem), however I think that may be a bit of a stretch.

The recommended replacement would also be an ABI break for existing libraries.

**Comment by iamdanfox** [comment]
Yeah that's a good point actually - you might conceivably have a `ThingsToDeleteSupplier extends Supplier<DeploymentId>` and `ThingsToCreateSupplier extends Supplier<DeploymentId>` and I'd much rather use the specific types rather than have two adjacent params somewhere that just say `Supplier<DeploymentId>`
