### ISSUE TITLE
Recommend `open *.ipr` after generating Intellij IDEA projects

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#321]
There are various different ways of importing java projects into intellij, but the only reliable one to get immutables generation working is to use `open *.ipr`

**Comment by mieubrisse** [comment]
Important note: it's not whether `open *.ipr` or the File > Open menu item from within IntelliJ that causes the Immutables generation issues, but instead what response was given to the "Import Unlinked Gradle Project?" popup in IntelliJ (coming from the IntelliJ Gradle plugin) right after opening the project. 

If "Do Not Import" is chosen, the org.inferred.processors Gradle plugin seems to do what it's supposed to and generated .java files get placed in `$module_root/generated_src` directories. If "Import" is chosen, everything goes weird - the generated .java files are placed in `$module_root/build/classes/java/my/package/path`, and they're not put on the classpath in IntelliJ so you won't be able to import them.

There should be a large warning that the Gradle Intellij plugin shouldn't be used, and a user with it installed should choose "Do Not Import". Otherwise, debugging why the generated files are being placed in `build/classes/java` instead of `generated_src` is very non-obvious and time-consuming.

**Comment by robert3005** [comment]
Just FYI - this behaves weirdly with latest EAP releases (2018.3), opens 2 windows where none of them have all the function bars

**Comment by carterkozak** [comment]
Closing, ipr is deprecated
