### ISSUE TITLE
checkNoUnusedPin deletes annotationProcessor, implementation, testImplementation deps

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#446]
## What happened

With baseline 0.37.4, @markelliot encountered a bug where running `./gradlew checkNoUnusedPin --fix` tried to delete a bunch of lines from the versions.props file:

```diff
-com.fasterxml.jackson.*:* = 2.9.7
-com.google.auto.service:* = 1.0-rc4
 com.google.guava:guava = 23.6.1-jre
-com.google.testing.compile:compile-testing = 0.15
-com.palantir.immutables.style:immutables-style = 1.2.0
-junit:junit = 4.12
-org.assertj:assertj-core = 3.11.1
-org.immutables:* = 2.7.1
-org.mockito:mockito-core = 2.23.0
-org.slf4j:* = 1.7.25
```

```gradle
dependencies {
    annotationProcessor 'com.palantir.immutables.style:immutables-style'
    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'

    implementation 'com.google.guava:guava'
    implementation 'org.slf4j:slf4j-api'

    testImplementation 'junit:junit'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
}
```

## What should have happened

None of these lines should have been deleted!

**Comment by robert3005** [comment]
https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java#L247 (https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph for details) with https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/versions/BaselineVersions.java#L128 are the cause of the issue here

**Comment by robert3005** [comment]
Well - this turns out not to be an issue since all those configs are part of some other that's visible and resolvable
