### ISSUE TITLE
Using your own internal classes shouldn't be considered a checkstyle violation

### ISSUE THREAD

**Issue by robert3005** [palantir/gradle-baseline#448]
After https://github.com/palantir/gradle-baseline/pull/445 any package that has `internal` in name will be flagged by checkstyle as violation. However, if you have internal packages in your project and depend on them in your tests (or even implementation since it's all internal to your project) then it shouldn't be considered a violation.

**Comment by iamdanfox** [comment]
Yeah - I think the checkstyle implementation we merged in https://github.com/palantir/gradle-baseline/pull/445 is a bit too simplistic... perhaps we should actually convert this into an errorprone check?

**Comment by robert3005** [comment]
What is the thing that you were trying to fix with this check? Imho if something is internal it either should be package scoped or not published

**Comment by iamdanfox** [comment]
The problem we're trying to solve is that in a widely used internal library (WC), there is a package hierarchy, but we only want people to use a few specific 'public API' classes.  Unfortunately Java requires us to make lots of the classes in deeper packages public so that the library itself can use them.

We refactored to put them in an 'internal' package so that people hopefully will not use them.

**Comment by iamdanfox** [comment]
OK so I think a good way forward would be to mark all the classes we don't want people to use with an annotation (like guava's `@Beta`) and then add some errorprone rules to discourage usage of them.

In fact, Google has already implemented this: https://github.com/google/guava-beta-checker

Unfortunately, I don't think we can use Guava's `@Beta` directly because there are way too many frequently used Guava classes that this would complain about (e.g. Streams, ByteSource).  https://github.com/google/guava/search?q=%22%40Beta%22&unscoped_q=%22%40Beta%22 This suggests we'd probably need to actually make up our own annotation to achieve this and fork the error-prone plugin.  

@rubenfiszel As this seems like quite a lot of overhead to prevent people using this stuff, I think it might be easier to just make all your new undertow related classes package-private for now.

**Comment by markelliot** [comment]
As an alternative, make this the first Java module conversion?

________________________________

**Comment by iamdanfox** [comment]
We're already tracking a stream of work to unblock Java 11 everywhere, but I don't think it's really feasible to block WC Undertow work on rolling out Java9+ on every dev machine.

A baby-step approach towards this would be to use Gradle's `api`/`implementation` stuff and put the other classes in a separate jar which will only appear in the pom.xml as a `runtime` dependency, but unfortunately all Gradle consumers will ignore this unless they have opted in using `enableFeaturePreview('IMPROVED_POM_SUPPORT')` or upgraded to Gradle 5.  We'll probably need to start excavating this to everyone (because it'll be on by default in Gradle 5), but I anticipate a lot of friction with that rollout.
