### ISSUE TITLE
Configure ideal ProjectRootManager to match project targetcompatibility

### ISSUE THREAD

**Issue by robert3005** [palantir/gradle-baseline#618]
## What happened?
Generate a project using java 11 via `./gradlew idea` that has targetCompatibility of 1.8. That then fails to compile in intellij with javac compilation failure

## What did you want to happen?
The compilation should succeed. One way to make this work is to make ProjectRootManager refer to 1.8 of jdk, though it's confusing why using java 11 causes intellij compilation to fail.

**Comment by diogoholanda** [comment]
The issue reported is also affecting me. From a previous discussion:

Since switching my default jdk to zulu11 I’ve been having problems with building projects in IntelliJ
Specifically, running `./gradlew clean idea` on develop and then trying to rebuild the project leads to an “internal java compile error”
`./gradlew compileJava` works
I’ve already changed the IntelliJ SDK to point to zulu11 as well
The language level is 8 for the project and all modules in IntelliJ
Changing IntelliJ’s SDK back to java8 makes it work again…

**Comment by diogoholanda** [comment]
I was able to make it work without changing the SDK back to 8.

The solution was to go to the compiler preferences and uncheck “Use compiler from module target JDK when possible”
