### ISSUE TITLE
Published jars should count lightweight tags towards version numbers

### ISSUE THREAD

**Issue by jonsyu1** [palantir/gradle-baseline#782]
## What happened?
```
$ git describe --tags
0.96.0
$ git describe
0.57.0-720-g7af14ede
$ ./gradlew publishToMavenLocal
```
published epoch2 API jars to `/home/jyu/.m2/repository/path/to/conjure/generated/api/0.57.0-720-g7af14ed`

## What did you want to happen?

```$ ./gradlew publishToMavenLocal```
should publish epoch2 API jars to `/home/jyu/.m2/repository/path/to/conjure/generated/api/0.96.0`

**Comment by jonsyu1** [comment]
The desired behavior happens in 1.16.0 and the undesired behavior happens in 1.17.0. These are the two PRs that went into 1.17.0:
* https://github.com/palantir/gradle-baseline/commit/f791ff98c67254e45c92aa277348b217880853cb
* https://github.com/palantir/gradle-baseline/commit/52988d8d3cd2af2585e3b3991ea90da19eba7ec3

I built gradle-baseline-java locally and tested against develop reverting these commits one at a time and confirmed that https://github.com/palantir/gradle-baseline/commit/f791ff98c67254e45c92aa277348b217880853cb caused the regression.

**Comment by ferozco** [comment]
I believe that the root cause here is that epoch2 was using a very old version of gradle-git-version (0.5.0) which was not resilient to the change in jgit version pulled in by baseline. More modern versions should work as intended. I've opened PRs to fix up excavator so it correctly upgrades gradle-git-version
